#generated by ai
import json
import os
import random

# Створюємо папку для наших файлів, якщо її ще немає
output_dir = "telephony_jsons"
os.makedirs(output_dir, exist_ok=True)

# Приклади описів від "LLM"
descriptions = [
    "Customer called to reset password. Issue resolved.",
    "User complained about slow internet speed. Ticket escalated to tech support.",
    "Billing inquiry regarding the last invoice. Clarified charges.",
    "Customer requested a refund for a defective product. Refund processed.",
    "Inquiry about new subscription plans. Information provided."
]

# Генеруємо 200 файлів
for call_id in range(1, 201):
    data = {
        "call_id": call_id,
        "duration_sec": random.randint(30, 1800), # Тривалість від 30 сек до 30 хв
        "short_description": random.choice(descriptions)
    }
    
    file_path = os.path.join(output_dir, f"call_{call_id}.json")
    
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)

print(f"Успішно згенеровано 200 JSON файлів у папці '{output_dir}'")

